### ISSUE TITLE
CRITICAL - wstunnel - Unable to start wstunnel. Process return a status code of: 2

### ISSUE THREAD

**Issue by cbjn** [klementng/wireguard-over-wstunnel#14]
I can run the client locally, but wgwst won't start wstunnel.

**Comment by klementng** [comment]
This is probably caused by the an old wstunnel instance not being closed properly causing the listening port be binded / being in used causing the new instance to fail to start. 

You could try, changing the listening port number 

```
wstunnel:
  ...
  - local-to-remote: udp://0.0.0.0:**NEW PORT**:127.0.0.1:51820?timeout_sec=0
```

Or open task manager and end all wstunnel instance

**Comment by klementng** [comment]
This commit 6cb8c1581fd0b72490392a0bf02cf7c3a0214b47 should fix the issue, you can download the binary here from https://github.com/klementng/wireguard-over-wstunnel/actions/runs/8400394659/artifacts/1352225397 and let me know if it is working
